### ISSUE TITLE
Not bottom

### ISSUE THREAD

**Issue by rockpaperscissorshoot** [realhackcraft/RPyG#1]
Caracter @ is not going all the way to the bottom. Don't believe me test it out yourself silly. I wouldn't lie. Are you back yet. See what I'm talking about. yeah don't doubt me again lil bro.

**Comment by realhackcraft** [comment]
Can confirm. I could reproduce the bug on my machine.

**Comment by realhackcraft** [comment]
@rockpaperscissorshoot paste this to vs code terminal

```
git fetch origin
git checkout 1-not-bottom
```

and then you can start fixing the issues.

Trust this is the better way.

**Comment by realhackcraft** [comment]
Then after that you can commit and push when you do changes.

when you done fixing this tell me
